### ISSUE TITLE
Report set 1 - countries

### ISSUE THREAD

**Issue by joannekennnedy** [LisaW831/Software_Engineering_dreamteam#1]

**Comment by joannekennnedy** [comment]
All the countries in the world organised by largest population to smallest.
All the countries in a continent organised by largest population to smallest.
All the countries in a region organised by largest population to smallest.

**Comment by joannekennnedy** [comment]
Tasks defined as user stories: 

As a locations advisor I want a report that shows all the countries in the world organised by largest population to smallest so I can advise which countries are the most populated and which countries are the least

**Comment by joannekennnedy** [comment]
Tasks defined as user stories:

As a locations advisor I want a report that shows all countries in a continent organised by largest population to smallest so I can advise which continents and which countries have the highest population and which have the lowest.

**Comment by LisaW831** [comment]
Suggested Query:

 public void getCountriesByPopulation() {
        try {
            // Create the SQL statement
            Statement stmt = con.createStatement();
            // Turn it into a string and add in the query. 
            String strSelect =
                    "SELECT Name, Population "
                    + "FROM Country "
                    + "ORDER BY Population DESC"; // Ordering by population in descending order
            // Run the SQL statement
            ResultSet rset = stmt.executeQuery(strSelect);
            // Print countries organized by population
            System.out.println("Countries by Population:");
            while (rset.next()) {
                String countryName = rset.getString("Name");
                int population = rset.getInt("Population");
                System.out.println(countryName + ": " + population);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("Failed to get country details");
             return null;
        }
    }

**Comment by joannekennnedy** [comment]
Report 1 output: 
![Screenshot (5)](https://github.com/LisaW831/Software_Engineering_dreamteam/assets/158073308/d2907539-fc9e-4e6d-b806-54491e7b176c)

**Comment by joannekennnedy** [comment]
Report 2 Output: 
![Screenshot (6)](https://github.com/LisaW831/Software_Engineering_dreamteam/assets/158073308/06ca4303-2bb7-45f5-9f99-cbfbde93e5de)

**Comment by joannekennnedy** [comment]
Report 3 Output: 
![Screenshot (7)](https://github.com/LisaW831/Software_Engineering_dreamteam/assets/158073308/ff365dd3-509b-4a30-b114-aaeccd638ae0)

**Comment by Gilleto123** [comment]
Report 1
![image.png](https://zube.io/files/semethods-2/bd235ef698669ef329726166e2e0e482-image.png)

Report 2

![image.png](https://zube.io/files/semethods-2/1ecf4aa04502d27fc24c43cd8afddddc-image.png)

Report 3

![image.png](https://zube.io/files/semethods-2/402cc8727353c2595f69c155d032e48d-image.png)
