### ISSUE TITLE
Report set 2 - Top N countries

### ISSUE THREAD

**Issue by joannekennnedy** [LisaW831/Software_Engineering_dreamteam#2]
The top N populated countries in the world where N is provided by the user.
The top N populated countries in a continent where N is provided by the user.
The top N populated countries in a region where N is provided by the user.

**Comment by Gilleto123** [comment]
Tasks defined as user stories:

As a locations advisor I want to be able to provide a colleague the top populated cities in a the world where the criteria is provided by the user

**Comment by Gilleto123** [comment]
Tasks defined as user stories:

As a locations advisor I want to be able to provide a colleague the top populated countries in a region where the criteria is provided by the user

**Comment by Gilleto123** [comment]
Report 4

![image.png](https://zube.io/files/semethods-2/91a92f419f0782b2c5c9db20fc5d25c6-image.png)


Report 5

![image.png](https://zube.io/files/semethods-2/0f29b7dda143fc0871aee4bf0468b515-image.png)


Report 6


![image.png](https://zube.io/files/semethods-2/f95f81a0794bfb16acbe608db5f08478-image.png)
