### ISSUE TITLE
Report set 3 - cities

### ISSUE THREAD

**Issue by joannekennnedy** [LisaW831/Software_Engineering_dreamteam#3]
All the cities in the world organised by largest population to smallest.
All the cities in a continent organised by largest population to smallest.
All the cities in a region organised by largest population to smallest.
All the cities in a country organised by largest population to smallest.
All the cities in a district organised by largest population to smallest.

**Comment by GRodger22** [comment]
Tasks defined as user stories.

As a locations advisor I want a report that shows all the cities in a continent organised by largest population to smallest to enable the organisation to make informed decisions for each continent based on city population.

**Comment by GRodger22** [comment]
Tasks defined as user stories.

As a locations advisor I want a report that shows all the cities in a country organised by largest population to smallest to enable the organisation to make informed decisions for each specified country based on city population.

**Comment by GRodger22** [comment]
Tasks defined as user stories.

As a locations advisor I want a report that shows all the cities in a district organised by largest population to smallest to enable the organisation to make informed decisions for each district based on city population.

**Comment by Gilleto123** [comment]
Report 7

![image.png](https://zube.io/files/semethods-2/882b9900158bbc1e2c2a65a4c6e020fc-image.png)

Report 8

![image.png](https://zube.io/files/semethods-2/3bd13c6d71b0dba05310c834e709080b-image.png)

Report 9

![image.png](https://zube.io/files/semethods-2/f20ac674fe6658a207eef8eb9d36fd88-image.png)

Report 10

![image.png](https://zube.io/files/semethods-2/88bf79c84554763116b66c1a309d3a7c-image.png)

Report 11
