### ISSUE TITLE
Suitable Integration tests defined

### ISSUE THREAD

**Issue by LisaW831** [LisaW831/Software_Engineering_dreamteam#32]

**Comment by LisaW831** [comment]
Integration tests:

1.Generate country report correctly:

Input: A country code.
Output: Verify that the generated country report contains the correct columns (Code, Name, Continent, Region, Population, Capital).

2.Generate city report correctly:

Input: A city name.
Output: Verify that the generated city report contains the correct columns (Name, Country, District, Population).

3.Generate capital city report correctly:

Input: A capital city name.
Output: Verify that the generated capital city report contains the correct columns (Name, Country, Population).

4. Generate population report for continent/region/country:

Input: Continent/region/country name.
Output: Verify that the generated population report contains the correct columns (Name, Total Population, Population in Cities (%), Population not in Cities (%)).

5.Generate language speakers report correctly:

Input: Language (Chinese, English, Hindi, Spanish, Arabic).
Output: Verify that the generated language speakers report contains the correct information, including the number of speakers and the percentage of the world population.

6.Generate top N populated countries report correctly:

Input: N (number of countries).
Output: Verify that the generated report contains the top N populated countries with the correct columns (Code, Name, Continent, Region, Population).

7.Generate top N populated cities report correctly:

Input: N (number of cities).
Output: Verify that the generated report contains the top N populated cities with the correct columns (Name, Country, District, Population).

8.Generate top N populated capital cities report correctly:

Input: N (number of capital cities).
Output: Verify that the generated report contains the top N populated capital cities with the correct columns (Name, Country, Population).

9.Generate country report and population report together:

Input: A country code.
Output: Verify that both country report and population report for the given country are generated correctly and contain consistent information.

10.Generate city report and population report together:

Input: A city name.
Output: Verify that both city report and population report for the given city are generated correctly and contain consistent information.

**Comment by GRodger22** [comment]
Integration Test 2:

@Test
    void generateCityDetails() {
        // Input
        String cityName = "New York";

        // Mock implementation of city details generation
        String[][] cityReport = generateCityDetails(cityName);

        // Output verification
        // Verify that the generated city details contains the correct columns
        assertEquals(4, cityReport[0].length); // 4 columns

        assertTrue(arrayTestValue(cityReport[0], "Name"));
        assertTrue(arrayTestValue(cityReport[0], "Country"));
        assertTrue(arrayTestValue(cityReport[0], "District"));
        assertTrue(arrayTestValue(cityReport[0], "Population"));
    }

    // Mock implementation of city details generation
    private String[][] generateCityDetails(String cityName) {
        return new String[][] {
                {"Name", "Country", "District", "Population"},
                {"New York", "USA", "New York", "8008278"}
        };
    }

    // method to check if an array contains a specific value
    private boolean arrayTestValue(String[] array, String value) {
        for (String item : array) {
            if (item.equals(value)) {
                return true;
            }
        }
        return false;
    }
