### ISSUE TITLE
Report set 4 - N populated cities

### ISSUE THREAD

**Issue by joannekennnedy** [LisaW831/Software_Engineering_dreamteam#4]
The top N populated cities in the world where N is provided by the user.
The top N populated cities in a continent where N is provided by the user.
The top N populated cities in a region where N is provided by the user.
The top N populated cities in a country where N is provided by the user.
The top N populated cities in a district where N is provided by the user.

**Comment by LisaW831** [comment]
Tasks defined as user stories:

As a locations advisor I want to be able to provide a colleague the top populated cities in the world where the criteria is provided by the user

**Comment by LisaW831** [comment]
Tasks defined as user stories:

As a locations advisor I want to be able to provide a colleague the top populated cities in a continent where the criteria is provided by the user

**Comment by LisaW831** [comment]
Tasks defined as user stories:

As a locations advisor I want to be able to provide a colleague the top populated cities in a region where the criteria is provided by the user

**Comment by LisaW831** [comment]
Tasks defined as user stories:

As a locations advisor I want to be able to provide a colleague the top populated cities in a country where the criteria is provided by the user

**Comment by LisaW831** [comment]
Tasks defined as user stories:

As a locations advisor I want to be able to provide a colleague the top populated cities in a district where the criteria is provided by the user

**Comment by LisaW831** [comment]
Report 12
![image.png](https://zube.io/files/semethods-2/8247578b587c9fd88ac8135d6f4e420c-image.png)

**Comment by LisaW831** [comment]
Report 13

![image.png](https://zube.io/files/semethods-2/5875ec7334c931d4727af5b0ffb95487-image.png)

**Comment by LisaW831** [comment]
Report 14

![image.png](https://zube.io/files/semethods-2/83821ae9543f7c536bcaf6062eb09d58-image.png)

**Comment by LisaW831** [comment]
Report 15

![image.png](https://zube.io/files/semethods-2/ec665b2b3fd789c201f907513c4cfc9e-image.png)

**Comment by LisaW831** [comment]
Report 16

![image.png](https://zube.io/files/semethods-2/4257e147aea93ab9b1a73f4b00448cb2-image.png)

**Comment by Gilleto123** [comment]
World Population:

![image.png](https://zube.io/files/semethods-2/5a9b4b7c6765f259a349ab4a9b9228a1-image.png)

**Comment by Gilleto123** [comment]
Country

![image.png](https://zube.io/files/semethods-2/7af324a87042b8bbe5e39ea0144db465-image.png)


City

![image.png](https://zube.io/files/semethods-2/a4fc17af9d3e6ca1e37c5de5ee1971c5-image.png)


Capital City

![image.png](https://zube.io/files/semethods-2/3daae42680eb723eec7bea3b89bcf27b-image.png)
