### ISSUE TITLE
Report set 5 - capital cities

### ISSUE THREAD

**Issue by joannekennnedy** [LisaW831/Software_Engineering_dreamteam#5]
All the capital cities in the world organised by largest population to smallest.
All the capital cities in a continent organised by largest population to smallest.
All the capital cities in a region organised by largest to smallest.

**Comment by joannekennnedy** [comment]
Tasks defined as user stories:

As a locations advisor I want a report that shows all the capital cities in the world organised by largest population to smallest so I can advise which capital cities have the largest population and which have the smallest.

**Comment by joannekennnedy** [comment]
Tasks defined as user stories:

As a locations advisor I want a report that shows all the capital cities in a continent organised by largest population to smallest so I can advise which continents have the largest population and which have the smallest.

**Comment by joannekennnedy** [comment]
Tasks defined as user stories:

As a locations advisor I want a report that shows all the capital cities in the region organised by largest population to smallest so I can advise which regions have the largest population and which have the smallest.

**Comment by joannekennnedy** [comment]
Report 17:
![Screenshot (8)](https://github.com/LisaW831/Software_Engineering_dreamteam/assets/158073308/7766dda8-95a3-4e5f-8d5b-e191b43ec688)

**Comment by joannekennnedy** [comment]
Report 18: 
![Screenshot (9)](https://github.com/LisaW831/Software_Engineering_dreamteam/assets/158073308/072ae442-e638-4e2e-8b7b-391789eb1f50)

**Comment by joannekennnedy** [comment]
Report 19:
![Screenshot (10)](https://github.com/LisaW831/Software_Engineering_dreamteam/assets/158073308/3e6419e8-cdad-403e-b0b6-62a4abd6b1d4)

**Comment by Gilleto123** [comment]
Report 17:

![image.png](https://zube.io/files/semethods-2/1d949d918507c35536d22a67e2a5c456-image.png)

Report 18:

![image.png](https://zube.io/files/semethods-2/c357bcb84eb7b12f8f4c3ab69112dbeb-image.png)

Report 19:

![image.png](https://zube.io/files/semethods-2/083b049cabe11476d265a278ecdf52ea-image.png)
