### ISSUE TITLE
Report set 6 - top N capital cities

### ISSUE THREAD

**Issue by joannekennnedy** [LisaW831/Software_Engineering_dreamteam#6]
The top N populated capital cities in the world where N is provided by the user.
The top N populated capital cities in a continent where N is provided by the user.
The top N populated capital cities in a region where N is provided by the user.

**Comment by Gilleto123** [comment]
Tasks defined as user stories:

As a locations advisor I want to be able to provide a colleague the top populated capital cities in the world where the criteria is provided by the user

**Comment by Gilleto123** [comment]
Tasks defined as user stories:

As a locations advisor I want to be able to provide a colleague the top populated capital cities in a continent where the criteria is provided by the user

**Comment by Gilleto123** [comment]
Tasks defined as user stories:

As a locations advisor I want to be able to provide a colleague the top populated capital cities in a region where the criteria is provided by the user

**Comment by Gilleto123** [comment]
Report 20

![image.png](https://zube.io/files/semethods-2/928f24adecb46b7eb2ffde91cb705d8c-image.png)


Report 21

![image.png](https://zube.io/files/semethods-2/a6513efb31be414cc6a3bab2b420c0cf-image.png)


Report 22

![image.png](https://zube.io/files/semethods-2/c4f889e246e5f10f18dcdf2ca961769f-image.png)
