### ISSUE TITLE
Report set 7 - population

### ISSUE THREAD

**Issue by joannekennnedy** [LisaW831/Software_Engineering_dreamteam#7]
The population of people, people living in cities, and people not living in cities in each continent.
The population of people, people living in cities, and people not living in cities in each region.
The population of people, people living in cities, and people not living in cities in each country.

**Comment by GRodger22** [comment]
Tasks defined as user stories.

As a locations advisor I want a report that shows population of people, people living in cities, and people not living in cities in each continent to enable the organisation to make informed decisions for each continent based on the output data.

**Comment by GRodger22** [comment]
Tasks defined as user stories.

As a locations advisor I want a report that shows population of people, people living in cities, and people not living in cities in each region to enable the organisation to make informed decisions for each region based on the output data.

**Comment by GRodger22** [comment]
Tasks defined as user stories.

As a locations advisor I want a report that shows population of people, people living in cities, and people not living in cities in each country to enable the organisation to make informed decisions for each country based on the output data.

**Comment by Gilleto123** [comment]
Report 7

![image.png](https://zube.io/files/semethods-2/af00d2d506be7a43bbb61ca472aff061-image.png)

**Comment by Gilleto123** [comment]
Report 8

![image.png](https://zube.io/files/semethods-2/d99d9126adc086c179eaacadd04765f0-image.png)

**Comment by Gilleto123** [comment]
Report 23

![image.png](https://zube.io/files/semethods-2/2cb24e32290856b2d1644996fe649aab-image.png)


Report 24

![image.png](https://zube.io/files/semethods-2/a428aef878da13633f752e2c9aa6ce38-image.png)


Report 25

![image.png](https://zube.io/files/semethods-2/c72ea0e22af2aa522eee1396cad38cbc-image.png)
