### ISSUE TITLE
Report set 8 - general population

### ISSUE THREAD

**Issue by joannekennnedy** [LisaW831/Software_Engineering_dreamteam#8]
The population of the world.
The population of a continent.
The population of a region.
The population of a country.
The population of a district.
The population of a city.

**Comment by LisaW831** [comment]
Tasks defined as user stories:

As a locations advisor I want to be able to provide a colleague data that shows the population of the world

**Comment by LisaW831** [comment]
Tasks defined as user stories:

As a locations advisor I want to be able to provide a colleague data that shows the population of a continent provided by the user

**Comment by LisaW831** [comment]
Tasks defined as user stories:

As a locations advisor I want to be able to provide a colleague data that shows the population of a region provided by the user

**Comment by LisaW831** [comment]
Tasks defined as user stories:

As a locations advisor I want to be able to provide a colleague data that shows the population of a country provided by the user

**Comment by LisaW831** [comment]
Tasks defined as user stories:

As a locations advisor I want to be able to provide a colleague data that shows the population of a district provided by the user

**Comment by LisaW831** [comment]
Tasks defined as user stories:

As a locations advisor I want to be able to provide a colleague data that shows the population of a city provided by the user

**Comment by LisaW831** [comment]
![image.png](https://zube.io/files/semethods-2/4edba8022a5dec07698bd2b0a2434b80-image.png)
