### ISSUE TITLE
Report set 9 - population who speak languages

### ISSUE THREAD

**Issue by joannekennnedy** [LisaW831/Software_Engineering_dreamteam#9]
Finally, the organisation has asked if it is possible to provide the number of people who speak the following the following languages from greatest number to smallest, including the percentage of the world population:

Chinese.
English.
Hindi.
Spanish.
Arabic.

**Comment by Gilleto123** [comment]
Tasks defined as user stories:

As a locations advisor I want a report sorted by greatest number to smallest from the list below, including the percentage of the world population, that provides the number of people who speak:
Chinese
English
Hindi
Spanish
Arabic

**Comment by Gilleto123** [comment]
Language Report

![image.png](https://zube.io/files/semethods-2/5cfa990676cc0872127b0e1fd768bd39-image.png)
